version: "3.7"

services:
  costura-postgres:
    image: postgres
    container_name: costura-postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=_,Gp70=i4|Kb
      - POSTGRES_DB=db_costura
    volumes:
      - pgdata:/data/postgres
    network_mode: host

  costura-server:
    container_name: costura-server
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.server
      target: production
    ports:
      - 3333:3333
      - 9229:9229
    volumes:
      - .:/usr/api
    network_mode: host
    depends_on:
      - costura-postgres

  costura-web:
    container_name: costura-web
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.web
      target: production
    ports:
      - 3000:3000
    volumes:
      - .:/usr/web
    network_mode: host
    depends_on:
      - costura-server

volumes:
  pgdata:
    driver: local
