version: "3.7"

services:
  costura-postgres:
    image: bitnami/postgresql:latest
    container_name: costura-postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=_,Gp70=i4|Kb
      - POSTGRES_DB=db_costura
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata:
    driver: local
