name: Build & Deploy Server

on:
  push:
    branches: [ main ]
    paths:
      - 'packages/server/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Install dependencies
        run: yarn

      - name: Run Tests
        run: yarn test:server

      - name: Run build
        run: cd packages/server && yarn build

      - name: Copy dist to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          source: ".,!node_modules"
          target: "~/app/mimas"

      - name: Run production scripts
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/app/mimas
            yarn
            cd ./packages/server
            ./node_modules/.bin/typeorm migration:run
            ./node_modules/.bin/typeorm-seeding/dist/cli.js seed
            pm2 restart costura-api
