name: Development Test

on:
  pull_request:
    branches:
      - develop
    paths:
      - 'packages/server/**'

jobs:
  testing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Install dependencies
        run: yarn

      - name: Run Tests
        run: yarn --cwd packages/server test
