name: Build & Deploy Server

on:
  push:
    branches:
      - main
    paths:
      - 'packages/server/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Run Tests
        run: yarn test:server
